[package]
name = "blinky"
version = "0.1.0"
authors = ["Konrad Krenzlin <git@krenzlin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
